language: c

git:
  depth: false

branches:
  only:
    - trunk

compiler:
  - gcc

before_install:
  - sudo pip install scons cpp-coveralls

script:
  - cd ${TRAVIS_BUILD_DIR}
  - scons coverage=yes
  - ./tests
  - gcov $(find . -type f -name "*.c")

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then coveralls --exclude test; fi'
