language: c

git:
  depth: 1

branches:
  only: trunk

os: linux

dist: bionic

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      scons
      gcc-10

compiler: gcc

before_script:
  - sudo rm /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-10 /usr/bin/gcc

script:
  - scons -C ${TRAVIS_BUILD_DIR}