name: Integration

on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install libgl-dev libx11-dev
      - run: make