name: Integration

on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cc: [gcc]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install libgl-dev libx11-dev libasound2-dev
        if: matrix.os == 'ubuntu-latest'
      - run: make
        env:
          CC: ${{ matrix.cc }}