name: Integration
on:
  push:
    branches: trunk
  pull_request:
    branches: trunk
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, cc: gcc }
          - { os: windows-latest, cc: cl }
          - { os: macos-latest, cc: clang }
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install libgl-dev libx11-dev libasound2-dev
        if: matrix.config.os == 'ubuntu-latest'
      - run: make
        if: matrix.config.os == 'ubuntu-latest' || matrix.config.os == 'macos-latest'
        env:
          CC: ${{ matrix.config.cc }}
      - uses: microsoft/setup-msbuild@v1
        if: matrix.config.os == 'windows-latest'
      - run: msbuild
        if: matrix.config.os == 'windows-latest'
      - run: tar -cvf neslika.tar neslika
        if: matrix.config.os == 'ubuntu-latest' || matrix.config.os == 'macos-latest'
      - run: tar -cvf neslika.tar neslika.exe
        if: matrix.config.os == 'windows-latest'
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: neslika.tar